plugins:
- '@typescript-eslint'

parser: '@typescript-eslint/parser'

parserOptions:
  sourceType: module

env:
  es6: true
  node: true

overrides:
  - files:
      - 'regression-tests/*.js'
    env:
      jest: true

rules:
  # possible errors
  for-direction: error
  getter-return: error
  no-async-promise-executor: error
  no-await-in-loop: off
  no-compare-neg-zero: error
  no-cond-assign: error
  no-console: off
  no-constant-condition: error
  no-control-regex: error
  no-debugger: error
  no-dupe-args: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-empty: error
  no-empty-character-class: error
  no-ex-assign: off
  no-extra-boolean-cast: error
  no-extra-parens: off 
  no-extra-semi: off
  no-func-assign: error
  no-inner-declarations: error
  no-invalid-regexp: error
  no-irregular-whitespace: error
  no-misleading-character-class: error
  no-obj-calls: error
  no-prototype-builtins: error
  no-regex-spaces: error
  no-sparse-arrays: error
  no-template-curly-in-string: error
  no-unexpected-multiline: error
  no-unreachable: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  require-atomic-updates: error
  use-isnan: error
  valid-typeof: error

  # best practices
  accessor-pairs: off
  array-callback-return: error
  block-scoped-var: error
  class-methods-use-this: off
  complexity: off
  consistent-return: off
  curly: [error, multi-line]
  default-case: off
  dot-location: [error, property]
  dot-notation: error
  eqeqeq: [error, smart]
  guard-for-in: off
  max-classes-per-file: off
  no-alert: error
  no-caller: error
  no-case-declarations: error
  no-div-regex: error
  no-else-return: error
  no-empty-function: error
  no-empty-pattern: error
  no-eq-null: off
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-fallthrough: error
  no-floating-decimal: off
  no-global-assign: error
  no-implicit-coercion: off
  no-implicit-globals: error
  no-implied-eval: error
  no-invalid-this: error
  no-iterator: error
  no-labels: error
  no-lone-blocks: error
  no-loop-func: error
  no-magic-numbers: off
  no-multi-spaces: error
  no-multi-str: error
  no-new: error
  no-new-func: error
  no-new-wrappers: error
  no-octal: error
  no-octal-escape: error
  no-param-reassign: off
  no-proto: error
  no-redeclare: error
  no-restricted-properties: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-assign: error
  no-self-compare: error
  no-sequences: error
  no-throw-literal: error
  no-unmodified-loop-condition: error
  no-unused-expressions: error
  no-unused-labels: error
  no-useless-call: error
  no-useless-catch: error
  no-useless-concat: error
  no-useless-escape: error
  no-useless-return: error
  no-void: error
  no-warning-comments: off
  no-with: error
  prefer-named-capture-group: off
  prefer-promise-reject-errors: error
  radix: error
  require-await: error
  require-unicode-regexp: off
  vars-on-top: off
  wrap-iife: error
  yoda: [error, never, {exceptRange: true}]

  # variables
  init-declarations: off
  no-delete-var: error
  no-label-var: error
  no-restricted-globals: off
  no-shadow: off
  no-shadow-restricted-names: off
  no-undef: error
  no-undef-init: error
  no-undefined: off
  no-unused-vars: error
  no-use-before-define: error

  # node
  callback-return: off
  global-require: error
  handle-callback-err: error
  no-buffer-constructor: error
  no-mixed-requires: error
  no-new-require: error
  no-path-concat: error
  no-process-env: error
  no-process-exit: error
  no-restricted-modules: off
  no-sync: off

  # style
  array-bracket-newline: off
  array-bracket-spacing: error
  array-element-newline: off
  block-spacing: [error, never]
  brace-style: error
  camelcase: off
  capitalized-comments: off
  comma-dangle: [error, always-multiline]
  comma-spacing: error
  comma-style: error
  computed-property-spacing: error
  consistent-this: off
  eol-last: error
  func-call-spacing: error
  func-name-matching: error
  func-names: off
  func-style: off
  function-paren-newline: error
  id-blacklist: off
  id-length: off
  id-match: off
  implicit-arrow-linebreak: error
  indent: off
  jsx-quotes: off
  key-spacing: error
  keyword-spacing: error
  line-comment-position: off
  linebreak-style: [error, unix]
  lines-around-comment: off
  lines-between-class-members: off
  max-depth: off
  max-len: off
  max-lines-per-function: off
  max-nested-callback: off
  max-params: off
  max-statements: off
  max-statements-per-line: off
  multiline-comment-style: error
  multiline-ternary: off
  new-cap: error
  new-parens: error
  newline-per-chained-call: off
  no-array-constructor: error
  no-bitwise: off
  no-continue: off
  no-inline-comments: off
  no-lonely-if: error
  no-mixed-operators: off
  no-multi-assign: off
  no-multiple-empty-lines: error
  no-negated-condition: off
  no-nested-ternary: off
  no-new-object: error
  no-plusplus: off
  no-restricted-syntax: off
  no-tabs: off
  no-ternary: off
  no-trailing-spaces: error
  no-underscore-dangle: error
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  nonblock-statement-body-position: error
  object-curly-newline: error
  object-curly-spacing: [error, always]
  object-property-newline: off
  one-var: [error, never]
  one-var-declaration-per-line: off
  operator-assignment: error
  operator-linebreak: off
  padded-blocks: [error, never]
  padding-line-between-statements: off
  prefer-object-spread: error
  quote-props: [error, as-needed]
  quotes: ["error", "single", { "allowTemplateLiterals": true }]
  require-jsdoc: off
  semi: error
  semi-spacing: error
  semi-style: error
  sort-keys: off
  sort-vars: off
  space-before-blocks: error
  space-before-function-paren: off
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: [error, {words: true, nonwords: false}]
  spaced-comment: error
  switch-colon-spacing: error
  template-tag-spacing: error
  unicode-bom: error
  wrap-regex: off

  # es6+
  arrow-body-style: error
  arrow-parens: [error, as-needed, {requireForBlockBody: true}]
  arrow-spacing: error
  constructor-super: error
  generator-star-spacing: [error, before]
  no-class-assign: error
  no-confusing-arrow: error
  no-const-assign: error
  no-dupe-class-members: error
  no-duplicate-imports: error
  no-new-symbol: error
  no-restricted-imports: off
  no-this-before-super: error
  no-useless-computed-key: error
  no-useless-constructor: error
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: off
  prefer-numeric-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: off
  require-yield: error
  rest-spread-spacing: error
  sort-imports: off
  symbol-description: error
  template-curly-spacing: error
  yield-star-spacing: error
