---
rules: # error | warning | off
  no-deprecated-resource: warning
  no-duplicate-env: error
  no-duplicate-param: error
  no-duplicate-resource: error
  no-extra-param: error
  no-invalid-dag: error
  no-invalid-name: error
  no-invalid-param-type: error
  no-latest-image: warning
  no-missing-param: error
  no-missing-resource: error
  no-missing-workspace: error
  no-pipeline-missing-parameters: error
  no-resourceversion: error
  no-undefined-param: error
  no-undefined-result: error
  no-undefined-volume: error
  no-unused-param: warning
  prefer-beta: warning
  prefer-kebab-case: warning
  prefer-when-expression: warning
