---
rules: # error | warning | off
  no-duplicate-param: error
  no-binding-missing-params: warning
  no-invalid-name: error
  no-params-api-mix: error
  no-pipeline-missing-parameters: error
  no-pipeline-missing-task: error
  no-pipeline-task-cycle: error
  no-extra-param: error
  no-pipeline-task-missing-params: error
  no-pipeline-task-missing-workspace: error
  no-undefined-result: error
  no-missing-param: error
  no-duplicate-resource: error
  no-resourceversion: error
  no-duplicate-env: error
  no-undefined-volume: error
  no-template-pipeline-missing-workspace: error
  no-wrong-param-type: error
  no-latest-image: warning
  prefer-beta-version: warning
  prefer-kebab-naming: warning
  no-unused-param: warning
  no-missing-resource: error
  no-undefined-param: error
