---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: no-duplicate-env-3
spec:
  stepTemplate:
    env:
      - name: FOO
        value: foo
  steps:
    - name: step-1
      image: alpine
      env:
        - name: FOO
          value: foo
      script: |
        #!/bin/sh

        echo ${FOO}
