---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: array-params
spec:
  params:
    - name: foo
      default:
        - foo
        - bar
    - name: bar
      default:
        - 1
        - bar
    - name: baz
      default:
        foo: bar
    - name: qux
      default: false
  steps: []
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: task-param-array-pipeline
spec:
  tasks:
    - name: task-param-array-task
      taskRef:
        name: doesnt-exist
      params:
        - name: compact-args
          value: ["first", "second"]
        - name: loose-args
          value:
            - "first"
            - "second"
