apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-test
spec:
  triggers:
    - binding:
        name: binding-missing
      template:
        name: template-missing
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener-2
spec:
  triggers:
      bindings:
       - name: binding
       - name: binding2
      template:
        name: template
