apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: image-versions
spec:
  steps:
    - name: ok
      image: node:13
    - name: not-ok
      image: node
    - name: also-not-ok
      image: node:latest
