---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: no-duplicate-param-1
spec:
  params:
    - name: foo
      value: foo
    - name: foo
      value: foo
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: no-duplicate-param-2
spec:
  params:
    - name: foo
    - name: foo
  tasks:
    - name: task
      taskSpec:
        params:
          - name: foo
          - name: foo
      params:
        - name: foo
          value: foo
        - name: foo
          value: foo
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: no-duplicate-param-3
spec:
  params:
    - name: foo
    - name: foo
  steps: []
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: no-duplicate-param-4
spec:
  params:
    - name: foo
    - name: foo
  resourcetemplates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: my-config
      data:
        foo: foo
        bar: bar
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipeline-run
      spec:
        pipelineSpec:
          params:
            - name: foo
            - name: foo
          tasks:
            - name: task
              taskSpec:
                params:
                  - name: foo
                  - name: foo
              params:
                - name: foo
                  value: foo
                - name: foo
                  value: foo
        params:
          - name: foo
            value: foo
          - name: foo
            value: foo
