---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: my-beta-task
spec:
  params:
    - name: my-param
    - name: my-unused-param
    - name: my-missing-pipeline-param
  steps:
    - name: my-step
      image: node:14
      env:
        - name: ENV_KEY
          value: $(params.my-param)
        - name: OTHER_ENV_KEY
          value: $(params.my-missing-param)
        - name: YET_ANOTHER_ENV_KEY
          value: $(params.my-missing-pipeline-param)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-beta-pipeline
spec:
  tasks:
    - name: my-pipeline-task
      taskRef:
        name: my-beta-task
      params:
        - name: my-param
          value: foo
        - name: my-unused-param
          value: foo
        - name: my-extra-param
          value: bar
    - name: my-other-pipeline-task
      taskSpec:
        params:
          - name: my-param
          - name: my-unused-param
          - name: my-missing-pipeline-param
        steps:
          - name: my-step
            image: node:14
            env:
              - name: ENV_KEY
                value: $(params.my-param)
              - name: OTHER_ENV_KEY
                value: $(params.my-missing-param)
              - name: YET_ANOTHER_ENV_KEY
                value: $(params.my-missing-pipeline-param)
      params:
        - name: my-param
          value: foo
        - name: my-unused-param
          value: foo
        - name: my-extra-param
          value: bar
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: my-task-with-workspace
spec:
  workspaces:
    - name: missing-task-workspace
  steps: []
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-pipeline-with-workspace
spec:
  tasks:
    - name: my-task
      taskRef:
        name: my-task-with-workspace
      workspaces:
        - name: my-workspace
          workspace: my-workspace
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-pipeline-with-workspace
spec:
  workspaces:
    - name: missing-pipeline-workspace
  tasks: []
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: my-trigger-template-with-workspace
spec:
  resourcetemplates:
    - kind: PipelineRun
      metadata:
        name: my-pipeline-run
      spec:
        pipelineRef:
          name: my-pipeline-with-workspace
