---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: condition-with-unused-params
spec:
  params:
    - name: left
      type: string
    - name: right
      type: string
  check:
    image: alpine
    script: |
      #!/bin/sh
      echo "condition-with-unused-params"
---
apiVersion: tekton.dev/v1alpha1
kind: Condition
metadata:
  name: condition-with-invalid-param-name
spec:
  params:
    - name: left!!
      type: string
  check:
    image: alpine
    script: |
      #!/bin/sh
      echo "condition-with-invalid-param-name"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-with-missing-condition
spec:
  tasks:
    - name: tekton-without-params
      taskRef:
        name: task-without-params
      conditions:
        - conditionRef: missing-condition
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-with-multiple-conditions
spec:
  tasks:
    - name: tekton-without-params
      taskRef:
        name: task-without-params
      conditions:
        - conditionRef: condition-with-unused-params
        - conditionRef: condition-with-unused-params
