---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: no-duplicate-param-1
spec:
  params:
    - name: triggerbinding-foo
      value: foo
    - name: triggerbinding-foo
      value: foo
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: no-duplicate-param-2
spec:
  params:
    - name: pipeline-foo
    - name: pipeline-foo
  tasks:
    - name: task
      taskSpec:
        params:
          - name: pipelinetask-foo
          - name: pipelinetask-foo
      params:
        - name: pipelinetask-foo
          value: foo
        - name: pipelinetask-foo
          value: foo
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: no-duplicate-param-3
spec:
  params:
    - name: task-foo
    - name: task-foo
  steps: []
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: no-duplicate-param-4
spec:
  params:
    - name: ttfoo
    - name: ttfoo
  resourcetemplates:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: my-config
      data:
        foo: foo
        bar: bar
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipeline-run
      spec:
        pipelineSpec:
          params:
            - name: psone
            - name: psone
          tasks:
            - name: task
              taskSpec:
                params:
                  - name: taskspec-foo
                  - name: taskspec-foo
              params:
                - name: taskspec-foo
                  value: $(params.psone)
                - name: taskspec-foo
                  value: $(params.psone)
        params:
          - name: psone
            value: $(tt.params.ttfoo)
          - name: psone
            value: $(tt.params.ttfoo)
