apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
  - name: branch
    value: $(event.pull_request.head.ref)
  - name: target-branch
    value: $(event.pull_request.base.ref)
  - name: pr-commit
    value: $(event.pull_request.head.sha)
  - name: pr-number
    value: $(event.pull_request.number)
