apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-lint
spec:
  inputs:
    params:
      - name: task-pvc
        description: the task pvc
  steps:
    - name: lint
      image: wcp-compliance-automation-team-docker-local.artifactory.swg-devops.com/ibm-compliance-automation:0.2
      env:
        - name: PIPELINE_RUN_URL
          valueFrom:
            configMapKeyRef:
              name: context
              key: PIPELINE_RUN_URL
        - name: PR_COMMIT
          valueFrom:
            configMapKeyRef:
              name: context
              key: PR_COMMIT

      command: ["/bin/bash", "-c"]
      workingDir: "/artifacts"
      args:
        - |
          set -e -o pipefail;
          source build.properties

          cd ./tekton-lint
          
          GHE_ORG=${REPOSITORY%/*}
          export GHE_ORG=${GHE_ORG##*/}
          export GIT_COMMIT=$PR_COMMIT
          export GHE_TOKEN
          export GHE_REPO=$REPO

          cocoa set-status --state="pending" --targetURL=$PIPELINE_RUN_URL --context="tekton/lint" --description="ESLint check is running."

          if npm run lint; then
            cocoa set-status --state="success" --targetURL=$PIPELINE_RUN_URL --context="tekton/lint" --description="ESLint check was successful."
          else
            cocoa set-status --state="failure" --targetURL=$PIPELINE_RUN_URL --context="tekton/lint" --description="ESLint check failed."
            exit 1
          fi

      volumeMounts:
        - mountPath: /artifacts
          name: task-volume

  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
