apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-setup-repo
spec:
  workspaces:
    - name: artifacts
      mountPath: /artifacts

  steps:
    - name: setup-repo
      image: ibmcom/pipeline-base-image:2.6
      command: ["/bin/bash", "-c"]
      env:
        - name: NODE_ENV
          value: development
      args:
        - |
          . /root/.nvm/nvm.sh
          set -e -o pipefail;

          echo "Setting up the repository."

          cd /artifacts/tekton-lint
          npm install
