apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-setup-repo
spec:
  inputs:
    params:
      - name: task-pvc
        description: the task pvc
  steps:
    - name: setup-repo
      image: ibmcom/pipeline-base-image:2.6
      env:
      - name: BRANCH
        valueFrom:
          configMapKeyRef:
            name: context
            key: BRANCH
      command: ["/bin/bash", "-c"]
      args:
        - |
          . /root/.nvm/nvm.sh
          set -e -o pipefail;

          echo "Setting up the repository."

          cd /artifacts/tekton-lint
          npm install

      volumeMounts:
        - mountPath: /artifacts
          name: task-volume

  volumes:
    - name: task-volume
      persistentVolumeClaim:
        claimName: $(inputs.params.task-pvc)
