apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-tekton-test
spec:
  params:
    - name: git-auth-user
      description: Git Authentication (it can be different for github, gitlab etc)
    - name: pipeline-debug
      description: Jesus walked this way
    - name: git-api-token-key
      description: github enterprise api token secret name
      default: "git-token"

  results:
    - name: exit-code
      description: The exit-code of the linting on pipelines and common-tekton-tasks together
    - name: status
      description: The status {"failure"|"success"} of the linting on pipelines and common-tekton-tasks together

  stepTemplate:
    env:
      - name: PIPELINE_DEBUG
        value: $(params.pipeline-debug)

  steps:
    - name: setup-test-repositories
      image: ibmcom/pipeline-base-image:2.6
      params:
        - name: GIT_AUTH_USER
          value: $(params.git-auth-user)
      command: ["/bin/bash", "-c"]
      workingDir: "/artifacts"
      args:
        - |
          set -e -o pipefail;

          if [ $PIPELINE_DEBUG == 1 ]; then
              pwd
              env
              trap env EXIT
              set -x
          fi

          echo "Cloning repositories..."
          GIT_TOKEN=$(cat "/secrets/$(params.git-api-token-key)")

          git clone https://GIT_AUTH_USER:$GIT_TOKEN@github.ibm.com/one-pipeline/common-tekton-tasks.git
          git clone https://GIT_AUTH_USER:$GIT_TOKEN@github.ibm.com/one-pipeline/compliance-cd-toolchain.git
          git clone https://GIT_AUTH_USER:$GIT_TOKEN@github.ibm.com/one-pipeline/compliance-ci-toolchain.git

    - name: tekton-test
      image: ibmcom/pipeline-base-image:2.6
      command: ["/bin/bash", "-c"]
      workingDir: "/artifacts"
      args:
        - |
          . /root/.nvm/nvm.sh
          cd ./tekton-lint
          npm link


          if [ $PIPELINE_DEBUG == 1 ]; then
              pwd
              env
              trap env EXIT
              set -x
          fi

          echo "Running tekton-lint on 'compliance-ci-toolchain', 'compliance-cd-toolchain', 'common-tekton-tasks'..."
          tekton-lint '../common-tekton-tasks/preview/*/*.(yaml|yml)' '../compliance-ci-toolchain/.pipeline/*.(yaml|yml)' '../compliance-cd-toolchain/.tekton/*.(yaml|yml)'

          if [ $? -eq 0 ]; then
            echo -n success | tee $(results.status.path)
            echo -n 0 | tee $(results.exit-code.path)
          else
            echo -n failure | tee $(results.status.path)
            echo -n 1 | tee $(results.exit-code.path)
          fi

  workspaces:
    - name: artifacts
      mountPath: /artifacts
    - name: secrets
      mountPath: /secrets
