name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 26
        uses: actions/setup-node@v6
        with:
          node-version: 26.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci

      - name: Update package.json version from tag
        run: |
             # Extracts '1.2.3' from 'refs/tags/v1.2.3'
             VERSION=${GITHUB_REF#refs/tags/v}
             npm version $VERSION --no-git-tag-version
      
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


            # - name: Release
            #   uses: softprops/action-gh-release@v1
            #   with:
            #     body_path: CHANGELOG.md
            #     append_body: true
            #     files: tekton-lint-*.tgz
