name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - uses: actions/checkout@v2
            - name: Use Node.js 20
              uses: actions/setup-node@v1
              with:
                node-version: 20.x
            - run: npm ci              
            - run: npm run build
            - run: npm pack

            - name: Release
              uses: softprops/action-gh-release@v1
              with: 
                body_path: CHANGELOG.md
                append_body: true
                files: tekton-lint-*.tgz
